Zitadel integration
datalens-tech/datalens-us pull request #116
Opened 2024-05-06 14:39 UTC by stankis

2024-05-13 22:32 UTC, stankis commented on src/types/models/common.ts
> +declare module '@gravity-ui/nodekit' {
absolutely agree, moved

2024-05-13 22:32 UTC, stankis commented on src/configs/common.ts
> +        Utils.getEnvVariable('ZITADEL') === Zitadel.Enabled
agree, done

2024-05-13 22:33 UTC, stankis commented on src/utils/zitadel.ts
> +        const response = await axios.post(
agree, done

2024-05-19 16:43 UTC, imsitnikov requested changes

2024-05-19 16:43 UTC, imsitnikov commented on src/middlewares/auth-zitadel.ts
> +import {NextFunction, Request, Response} from '@gravity-ui/expresskit';
We already have folder for middlwares – `src/components/middlewares`.

2024-05-19 16:43 UTC, imsitnikov commented on src/middlewares/auth-zitadel.ts
> +            return next();
Need to save `r2.name` in `req.locals` and add it into `"info"` context here – `src/components/middlewares/ctx.ts`.

2024-05-20 20:47 UTC, stankis commented on src/middlewares/auth-zitadel.ts
> +import {NextFunction, Request, Response} from '@gravity-ui/expresskit';
agree, moved, didn't find at first glance )

2024-05-20 21:28 UTC, stankis commented on src/utils/zitadel.ts
> +axiosRetry(axios, {
Discussed offline, fixed

2024-05-20 21:29 UTC, stankis commented on dev/env/opensource/development.env
> +ZITADEL_URI=http://localhost:8085
of course I will

2024-05-20 21:34 UTC, stankis commented on src/middlewares/auth-zitadel.ts
> +            return next();
Added

2024-06-03 10:24 UTC, jhoncool approved these changes

2024-06-03 12:14 UTC, jhoncool commented on src/const/common.ts
> +export const DL_SERVICE_USER_ACCESS_TOKEN = 'x-dl-service-user-access-token';
Let's add it to appSensitiveKeys, appSensitiveHeaders

2024-06-03 12:56 UTC, jhoncool commented
I don't see how can we get some info about current user. For example userId

2024-06-03 22:20 UTC, stankis commented on src/const/common.ts
> +export const DL_SERVICE_USER_ACCESS_TOKEN = 'x-dl-service-user-access-token';
done

2024-06-03 22:24 UTC, stankis commented
> I don't see how can we get some info about current user. For example userId

r1.name for instance. If we need I may extract more info

2024-06-04 08:23 UTC, jhoncool commented
> > I don't see how can we get some info about current user. For example userId
> 
> r1.name for instance. If we need I may extract more info: https://github.com/datalens-tech/datalens-us/pull/116/files#diff-33b5439ed457fcad5bd3cd5f870b8c1fcead6ceded5fe3964d923f5e5f87c718R14

Yes we need userId for DLS

2024-06-04 21:43 UTC, stankis commented
> > > I don't see how can we get some info about current user. For example userId
> > 
> > 
> > r1.name for instance. If we need I may extract more info: https://github.com/datalens-tech/datalens-us/pull/116/files#diff-33b5439ed457fcad5bd3cd5f870b8c1fcead6ceded5fe3964d923f5e5f87c718R14
> 
> Yes we need userId for DLS

Added userId to req

2024-06-05 06:48 UTC, jhoncool commented
> > > > I don't see how can we get some info about current user. For example userId
> > > 
> > > 
> > > r1.name for instance. If we need I may extract more info: https://github.com/datalens-tech/datalens-us/pull/116/files#diff-33b5439ed457fcad5bd3cd5f870b8c1fcead6ceded5fe3964d923f5e5f87c718R14
> > 
> > 
> > Yes we need userId for DLS
> 
> Added userId to req

In our case it should be in res.locals and received in ctx middleware https://github.com/datalens-tech/datalens-us/blob/main/src/components/middlewares/ctx.ts#L9-L10

2024-06-05 08:52 UTC, stankis commented
> > > > > I don't see how can we get some info about current user. For example userId
> > > > 
> > > > 
> > > > r1.name for instance. If we need I may extract more info: https://github.com/datalens-tech/datalens-us/pull/116/files#diff-33b5439ed457fcad5bd3cd5f870b8c1fcead6ceded5fe3964d923f5e5f87c718R14
> > > 
> > > 
> > > Yes we need userId for DLS
> > 
> > 
> > Added userId to req
> 
> In our case it should be in res.locals and received in ctx middleware https://github.com/datalens-tech/datalens-us/blob/main/src/components/middlewares/ctx.ts#L9-L10

I guess this is what you want : https://github.com/datalens-tech/datalens-us/pull/116/files#diff-33b5439ed457fcad5bd3cd5f870b8c1fcead6ceded5fe3964d923f5e5f87c718R26

2024-06-05 09:09 UTC, jhoncool approved these changes

2024-06-05 17:31 UTC, imsitnikov approved these changes

2024-06-07 09:19 UTC, melikhov-dev commented on dev/env/opensource/development.env
> +SERVICE_CLIENT_SECRET=bB6PrbvqgOjnBh5aoTQNZPFE7dysSnSAfZ2Li7vpJwp0AzamSxZNkA0guvkWrtz1
Very common names. It is not clear from the name what they are needed for.

2024-06-07 09:20 UTC, melikhov-dev commented on src/configs/common.ts
> +    clientSecret: Utils.getEnvVariable('CLIENT_SECRET') || '',
Very common names. It is not clear from the name what they are needed for.

2024-06-07 11:36 UTC, jhoncool approved these changes

2024-06-07 13:07 UTC, imsitnikov approved these changes

2024-06-07 13:44 UTC, stankis commented on dev/env/opensource/development.env
> +SERVICE_CLIENT_SECRET=bB6PrbvqgOjnBh5aoTQNZPFE7dysSnSAfZ2Li7vpJwp0AzamSxZNkA0guvkWrtz1
Please suggest new names, will fix within CHARTS-9785

2024-06-07 13:44 UTC, stankis commented on src/configs/common.ts
> +    clientSecret: Utils.getEnvVariable('CLIENT_SECRET') || '',
Please suggest new names, will fix within CHARTS-9785

2024-06-07 13:50 UTC, merged