Charts 9608 mass remove collections and workbooks
datalens-tech/datalens-us pull request #129
Opened 2024-06-13 15:03 UTC by Sergey-weber

2024-06-23 16:13 UTC, imsitnikov requested changes

2024-06-23 16:13 UTC, imsitnikov commented on src/services/new/workbook/delete-workbooks.ts
> +            await workbook.checkPermission({
This check will be thrown in the background. App will crash and I'm not sure what will happen with the deleted workbooks, perhaps they can be deleted without `delete` permission.

This check should be like that:
```ts
const checkDeletePermissionPromises = workbooks.map(async (workbook) => {
    ...
});

await Promise.all(checkDeletePermissionPromises);
```

2024-06-23 16:16 UTC, imsitnikov requested changes

2024-06-23 16:16 UTC, imsitnikov commented on src/routes.ts
> +                route: 'DELETE /v1/delete-workbooks',
`/v1/delete-workbooks` -> `/v2/delete-workbooks`
it doesn't make any real sense, but for consistency with other workbook routes.

2024-06-23 16:17 UTC, imsitnikov commented
@Sergey-weber add integrational tests in closed repo plz, for delete and move routes.

2024-07-02 09:59 UTC, Sergey-weber commented on src/services/new/workbook/delete-workbooks.ts
> +            await workbook.checkPermission({
Yes, I didn't know about it, fixed it

2024-07-03 18:33 UTC, imsitnikov requested changes

2024-07-03 18:33 UTC, imsitnikov commented on src/services/new/collection/get-collections-list-by-ids.ts
> +        collectionIds: await Utils.macrotasksMap(collectionIds, (id) => Utils.encodeId(id)),
`await Utils.macrotasksMap(collectionIds, (id) => Utils.encodeId(id))` -> `await Utils.macrotasksMap(models.map((item) => item.collectionId), (id) => Utils.encodeId(id))`

to log only fetched collection ids

2024-07-03 18:33 UTC, imsitnikov commented on src/services/new/collection/get-collection.ts
> +        permission: {
Where is it used?

2024-07-04 12:11 UTC, Sergey-weber commented on src/services/new/collection/get-collection.ts
> +        permission: {
now nowhere, but service getCollection now use checkAndSetCollectionPermission, where u can check specific permission, it would be useful in the future, if you wanna get collection and check specific permission

2024-07-04 13:51 UTC, imsitnikov commented on src/services/new/collection/get-collection.ts
> +        permission: {
ok

2024-07-07 12:24 UTC, imsitnikov approved these changes

2024-07-07 12:24 UTC, imsitnikov commented on src/controllers/workbooks.ts
> +        const formattedResponse = formatWorkbookModelsList(result);
don't forget to change `DeleteWorkbookResponse` type in `datalens-ui` repo.

2024-07-08 07:37 UTC, merged