Add checking displayKey for parent folder
datalens-tech/datalens-us pull request #13
Opened 2023-10-17 12:32 UTC by Sergey-weber

Added a check for the equality of the display_key with the key from input parameter

2023-10-17 17:34 UTC, imsitnikov requested changes

2023-10-17 17:34 UTC, imsitnikov commented on src/db/models/entry/index.ts
>                      .first();
Looks like the single change what should be in this PR:
```
parentFolder = await Entry.query(TRX)
    .select(RETURN_COLUMNS)
    .join('revisions', 'entries.savedId', 'revisions.revId')
    .where({
        tenantId,
        displayKey: Utils.getParentFolderKey({keyFormatted: displayKey}), // <- here
        isDeleted: false,
    })
    .first();
```

2023-10-17 17:34 UTC, imsitnikov commented on src/db/models/entry/index.ts
> +        console.log('keyasd: ', key);
?

2023-10-18 09:07 UTC, Sergey-weber commented on src/db/models/entry/index.ts
> +        console.log('keyasd: ', key);
removed

2023-10-18 09:07 UTC, Sergey-weber commented on src/db/models/entry/index.ts
>                      .first();
yea, usually we use query with key, i don't know why, fixed it

2023-10-18 11:26 UTC, jhoncool approved these changes

2023-10-18 12:56 UTC, imsitnikov approved these changes

2023-10-18 14:47 UTC, merged