Added vertical roles for oss
datalens-tech/datalens-us pull request #151
Opened 2024-07-02 22:24 UTC by stankis

2024-07-03 08:17 UTC, imsitnikov requested changes

2024-07-03 08:17 UTC, imsitnikov commented on src/services/new/collection/get-collection-root-permissions.ts
> +        createWorkbookInRoot: false,
why? If `accessServiceEnabled = false`, we should return `true`for both flags.

2024-07-03 08:17 UTC, imsitnikov commented on src/services/new/collection/get-collection-content.ts
> -                        collection.enableAllPermissions();
Why did you remove using of `enableAllPermissions` everywhere?

2024-07-03 10:30 UTC, stankis commented on src/services/new/collection/get-collection-root-permissions.ts
> +        createWorkbookInRoot: false,
discussed offline, reverted

2024-07-03 10:30 UTC, stankis commented on src/services/new/collection/get-collection-content.ts
> -                        collection.enableAllPermissions();
discussed offline, reverted

2024-07-04 08:57 UTC, imsitnikov requested changes

2024-07-04 08:57 UTC, imsitnikov commented on src/registry/common/entities/collection/collection.ts
> +            listAccessBindings: isEditorOrAdmin,
`listAccessBindings: true`
it doesn't affect anything in oss role model, but it makes more sense.

2024-07-04 08:57 UTC, imsitnikov commented on src/utils/zitadel.ts
> +    if (roles['datalens.admin']) {
Can we reuse `ZitadelUserRole.Admin` instead of `'datalens.admin'` here?

2024-07-04 08:57 UTC, imsitnikov commented on src/registry/common/entities/collection/collection.ts
> +    async checkPermission(args: {
By default we support installation without zitadel – https://github.com/datalens-tech/datalens/blob/main/docker-compose.yml

Are you sure that installation will work after updating datalens-us with these changes?

2024-07-04 13:10 UTC, stankis commented on src/utils/zitadel.ts
> +    if (roles['datalens.admin']) {
of course, fixed

2024-07-04 13:14 UTC, stankis commented on src/registry/common/entities/collection/collection.ts
> +            listAccessBindings: isEditorOrAdmin,
ok, let's change to listAccessBindings: true

2024-07-07 11:52 UTC, imsitnikov approved these changes

2024-07-07 13:55 UTC, merged