Add method - getEntriesWithPermissionsOnly
datalens-tech/datalens-us pull request #168
Opened 2024-08-13 11:41 UTC by Sergey-weber

2024-09-08 11:44 UTC, imsitnikov requested changes

2024-09-08 11:44 UTC, imsitnikov commented on src/utils/entry.ts
> +    {entries, includePermissionsInfo, isPrivateRoute}: GetEntriesWithPermissionsOnlyArgs,
`isPrivateRoute` can be obtained as `const {isPrivateRoute} = ctx.get('info');`

2024-09-08 11:44 UTC, imsitnikov commented on src/utils/entry.ts
> +export const getEntriesWithPermissionsOnly = async (
let's rename the method to `filterEntriesByPermission` and add the ability to use a different permission filter.

2024-09-08 11:44 UTC, imsitnikov commented on src/utils/entry.ts
> +    entries: EntryWithPermissionOnly[];
let's use a generic type for `entries`:

```ts
type FilterEntriesByPermissionArgs<T> = {
    entries: T[];
    permission?: Permission;
    includePermissionsInfo?: boolean;
};

type EntryWithPermissions<T> = T & {isLocked: boolean; permsisions?: EntryPermissions};

type FilterEntriesByPermissionResult<T> = Promise<EntryWithPermissions<T>[]>;
```

2024-09-08 11:44 UTC, imsitnikov commented on src/utils/entry.ts
> +    const entryWithoutWorkbook: EntryWithPermissionOnly[] = [];
`entryWithoutWorkbook` -> `folderEntries`

2024-09-08 11:44 UTC, imsitnikov commented on src/utils/entry.ts
> +                            isLocked = true;
Usage `isLocked: true` for workbook entries leads to ability to open incorrect request permissions dialog:

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/955177d3-db12-4c4a-928e-7df0065e8373">

For now would be better to hide such entries.

2024-09-08 11:44 UTC, imsitnikov commented on src/utils/entry.ts
> +};
If we decide to refact this code and make separate method, let's make it more tidy and similar to other service utility methods and put it to `src/services/new/entry/utils`.

Untested code (with changes from the comments above):

```ts
import {DlsActions} from '../types/models/dls';
import {ServiceArgs} from '../services/new/types';
import {getReplica} from '../services/new/utils';
import type {EntryScope} from '../types/models/entry';
import {getWorkbooksListByIds} from '../services/new/workbook/get-workbooks-list-by-ids';
import type {EntryPermissions} from '../services/new/entry/types';
import type {WorkbookInstance} from '../registry/common/entities/workbook/types';
import {getEntryPermissionsByWorkbook} from '../services/new/workbook/utils';
import {registry} from '../registry';

type Permission = 'execute' | 'read' | 'edit' | 'admin';

const DLSPermissionsMap: Record<Permission, DlsActions> = {
    execute: DlsActions.Execute,
    read: DlsActions.Read,
    edit: DlsActions.Edit,
    admin: DlsActions.SetPermissions,
};

type PartialEntry = {
    entryId: string;
    scope: string;
    workbookId: string | null;
};

type FilterEntriesByPermissionArgs<T> = {
    entries: T[];
    permission?: Permission;
    includePermissionsInfo?: boolean;
};

type EntryWithPermissions<T> = T & {isLocked: boolean; permsisions?: EntryPermissions};

type FilterEntriesByPermissionResult<T> = Promise<EntryWithPermissions<T>[]>;

export const filterEntriesByPermission = async <T extends PartialEntry>(
    {ctx, trx}: ServiceArgs,
    args: FilterEntriesByPermissionArgs<T>,
): FilterEntriesByPermissionResult<T> => {
    const {entries, permission = 'read', includePermissionsInfo} = args;

    const {isPrivateRoute} = ctx.get('info');

    const result: EntryWithPermissions<T>[] = [];

    const workbookEntries: T[] = [];
    const folderEntries: T[] = [];

    entries.forEach((entry) => {
        if (entry.workbookId) {
            workbookEntries.push(entry);
        } else {
            folderEntries.push(entry);
        }
    });

    if (folderEntries.length > 0) {
        if (!isPrivateRoute && ctx.config.dlsEnabled) {
            const {DLS} = registry.common.classes.get();

            result.push(
                ...(await DLS.checkBulkPermission(
                    {ctx, trx: getReplica(trx)},
                    {
                        entities: folderEntries,
                        action: DLSPermissionsMap[permission],
                        includePermissionsInfo,
                    },
                )),
            );
        } else {
            result.push(
                ...folderEntries.map((entry) => ({
                    ...entry,
                    isLocked: false,
                    ...(includePermissionsInfo
                        ? {
                              permissions: {
                                  execute: true,
                                  read: true,
                                  edit: true,
                                  admin: true,
                              },
                          }
                        : {}),
                })),
            );
        }
    }

    if (workbookEntries.length > 0) {
        if (!isPrivateRoute && ctx.config.accessServiceEnabled) {
            const workbookIds = new Set<string>();

            workbookEntries.forEach((entry) => {
                if (entry.workbookId) {
                    workbookIds.add(entry.workbookId);
                }
            });

            const availableWorkbooks = await getWorkbooksListByIds(
                {ctx, trx: getReplica(trx)},
                {
                    workbookIds: [...workbookIds],
                    includePermissionsInfo,
                },
            );

            const availableWorkbooksMap = new Map<string, WorkbookInstance>();

            availableWorkbooks.forEach((workbook) => {
                availableWorkbooksMap.set(workbook.model.workbookId, workbook);
            });

            workbookEntries.forEach((entry) => {
                if (entry?.workbookId && availableWorkbooksMap.has(entry.workbookId)) {
                    const workbook = availableWorkbooksMap.get(entry.workbookId);

                    let permissions: Optional<EntryPermissions>;

                    if (workbook && includePermissionsInfo) {
                        permissions = getEntryPermissionsByWorkbook({
                            ctx,
                            workbook,
                            scope: entry.scope as EntryScope,
                        });

                        if (permissions[permission]) {
                            result.push({
                                ...entry,
                                isLocked: false,
                                permissions,
                            });
                        }
                    }
                }
            });
        } else {
            result.push(
                ...workbookEntries.map((entry) => ({
                    ...entry,
                    isLocked: false,
                    ...(includePermissionsInfo
                        ? {
                              permissions: {
                                  execute: true,
                                  read: true,
                                  edit: true,
                                  admin: true,
                              },
                          }
                        : {}),
                })),
            );
        }
    }

    const orderedResult: EntryWithPermissions<T>[] = [];

    entries.forEach((entry) => {
        const resultEntry = result.find((item) => entry.entryId === item.entryId);
        if (resultEntry) {
            orderedResult.push(resultEntry);
        }
    });

    return orderedResult;
};
```

2024-09-09 09:58 UTC, Sergey-weber commented on src/utils/entry.ts
> +    entries: EntryWithPermissionOnly[];
it seems to me that this is not necessary, the function should accept only the data that it needs to work, let's leave the EntryWithPermissionOnly type

2024-09-09 12:49 UTC, Sergey-weber commented on src/utils/entry.ts
> +                            isLocked = true;
this is also reproduce in main branch and it only possible if we have added an entry to favorites, for example, with permission to view in the workbook, and after some administrator changes the permission on workbook from view to limited viewing, we will see a locked entry in favorites, also this it is possible only with datasets and connections. I think we should fix it in the interface part, I can fix it in the us, but not in this method, it's better to filter them in the favorites service. But if we fix it we will hide locked entry, better to fix these on frontend part

2024-09-09 12:51 UTC, Sergey-weber commented on src/utils/entry.ts
> +};
these code doesn't work correctly, because some services waiting entries with isLocked for workbook entries, I took some things from these code, like permission in args

2024-09-10 13:54 UTC, Sergey-weber commented on src/utils/entry.ts
> +};
also was bug with includePermissionsInfo, fixed it

2024-09-11 20:03 UTC, imsitnikov requested changes

2024-09-11 20:57 UTC, Sergey-weber commented on src/db/models/navigation/index.ts
> +            ctx.log('GET_ENTRIES_REQUEST_SUCCESS');
I don't see anything wrong here, we return different data depending on the condition, I think it's better to leave it as it is

2024-09-11 20:58 UTC, Sergey-weber commented on src/services/new/entry/utils/filter-entries-by-permission.ts
> +type EntryWithPermissions<T> = T & {isLocked?: boolean; permsisions?: EntryPermissions};
it is optional parameters, let's leave it as it is

2024-09-12 08:26 UTC, Sergey-weber commented on src/services/new/entry/utils/filter-entries-by-permission.ts
> +type EntryWithPermissions<T> = T & {isLocked?: boolean; permsisions?: EntryPermissions};
https://github.com/datalens-tech/datalens-us/blob/main/src/types/models/dls.ts#L90

2024-09-12 10:39 UTC, jhoncool approved these changes

2024-09-12 12:13 UTC, merged