Single list for structure items, like collections and workbooks.
datalens-tech/datalens-us pull request #171
Opened 2024-08-21 09:16 UTC by TheXardas

- New endpoint added: /v1/structure-items
- Allows for single ui flat infinite scroll fetch
- Old endpoint is deprecated, and should be removed, upon successful UI integration

2024-08-21 18:28 UTC, imsitnikov requested changes

2024-08-21 18:28 UTC, imsitnikov commented on src/services/new/structure-item/get-collections-query.ts
> +export const getCollectionsQuery = ({ctx, trx}: ServiceArgs, args: GetCollectionsQueryArgs) => {
Let's put `getCollectionsQuery` and `getWorkbooksQuery` to `src/services/new/structure-item/utils/` folder. They are not independent service methods and cannot be called from controllers.

2024-08-21 18:28 UTC, imsitnikov commented on src/services/new/structure-item/get-structure-items.ts
> +const processPermissions = async ({
And these methods (`processPermissions`, `isWorkbookModel`, `bulkFetchStructureItemsAllPermissions`, etc) would be better to place in `src/services/new/structure-item/utils/`.

2024-08-22 14:47 UTC, jhoncool commented on src/services/new/structure-item/utils.ts
> +            type: raw("'workbook'"),
Can you use select with array and cast like 
```js
select([raw("'collection' AS ??", 'type'), raw('null AS ??', 'parentId'), WorkbookModelColumn.CollectionId, ...])
```
Otherwise it looks like `select "workbookId" as "workbookId", "collectionId" as "collectionId", ...` in the sql query.

2024-08-22 14:47 UTC, jhoncool commented on src/services/new/structure-item/utils.ts
> +    const collectionsById: {[k: string]: CollectionInstance} = {};
`[k: string]` -> `[id: string]` 
id or collectionId

2024-08-23 08:29 UTC, jhoncool approved these changes

2024-08-23 09:18 UTC, imsitnikov approved these changes

2024-08-23 09:36 UTC, merged