Add mode save, publish for creating entry
datalens-tech/datalens-us pull request #175
Opened 2024-08-30 13:08 UTC by Sergey-weber

2024-09-01 17:51 UTC, imsitnikov requested changes

2024-09-01 17:51 UTC, imsitnikov commented on src/services/entry.service.ts
> +            return await createEntryInWorkbook(ctx, {
Need to support `mode` param in `_create` and `entriesController._createEntry`.

2024-09-01 17:51 UTC, imsitnikov commented on src/db/models/entry/index.ts
> +            const patchData = {
`patchData` -> `data`? It's not a patch, but a full set of fields.

2024-09-01 17:51 UTC, imsitnikov commented on src/services/entry/actions/create-in-workbook.ts
> +        const patchData = {
`patchData` -> `data`

2024-09-05 09:29 UTC, Sergey-weber commented on src/db/models/entry/index.ts
> +            const patchData = {
changed on newData, because data already declared

2024-09-05 09:29 UTC, Sergey-weber commented on src/services/entry/actions/create-in-workbook.ts
> +        const patchData = {
changed on newData

2024-09-05 15:03 UTC, merged