Add new method deleteWorkbooksList
datalens-tech/datalens-us pull request #197
Opened 2024-11-05 13:22 UTC by Sergey-weber

2024-11-06 19:20 UTC, imsitnikov requested changes

2024-11-06 19:20 UTC, imsitnikov commented on src/registry/common/entities/collection/collection.ts
> +        this.permissions = undefined;
There is no need to clear `this.permissions` here. These methods only for clearing permissions in external services.

2024-11-06 19:20 UTC, imsitnikov commented on src/services/new/collection/delete-collections.ts
> +        {collectionIds: collectionsForDeleteIds, permission: CollectionPermission.Delete},
We start checking the `delete` permission for every collection in the tree, this is wrong, we only need to check direct deleting collections.

2024-11-06 19:20 UTC, imsitnikov commented on src/services/new/collection/delete-collections.ts
> +        if (workbook.isTemplate) {
Looks like this check already exists in the `deleteWorkbooks` method.

2024-11-07 09:47 UTC, Sergey-weber commented on src/services/new/collection/delete-collections.ts
> +        {collectionIds: collectionsForDeleteIds, permission: CollectionPermission.Delete},
yes, fixed it

2024-11-07 09:51 UTC, Sergey-weber commented on src/services/new/collection/delete-collections.ts
> +        if (workbook.isTemplate) {
yes, but there is a more informative error - "Collection with workbook template can't be deleted"? and if we fall here, will we not have to request workbooks once again.  this code was already there, I just moved it

2024-11-07 22:04 UTC, imsitnikov requested changes

2024-11-08 08:54 UTC, imsitnikov approved these changes

2024-11-08 09:09 UTC, merged