Add data export migration
datalens-tech/datalens-us pull request #223
Opened 2024-12-19 10:36 UTC by sjorobekov

2024-12-25 19:02 UTC, imsitnikov requested changes

2024-12-25 19:02 UTC, imsitnikov commented on src/db/migrations/20241219092946_data_export.ts
> +            chart_id BIGINT NOT NULL,
Need to add indexes for `chart_id`, `dataset_id`, `connection_id` and `expired_at`

2024-12-26 15:19 UTC, sjorobekov commented on src/db/migrations/20241219092946_data_export.ts
> +            chart_id BIGINT NOT NULL,
Done

2024-12-27 10:15 UTC, imsitnikov requested changes

2024-12-27 10:15 UTC, imsitnikov commented on src/db/migrations/20241219092946_data_export.ts
> +            dataset_rev_id BIGINT NOT NULL,
If `dataset_id` is nullable, we need to make  `dataset_rev_id` nullable too.

2024-12-27 10:25 UTC, sjorobekov commented on src/db/migrations/20241219092946_data_export.ts
> +            dataset_rev_id BIGINT NOT NULL,
updated

2024-12-27 11:14 UTC, imsitnikov requested changes

2024-12-27 11:14 UTC, imsitnikov commented on src/db/models/new/data-export/index.ts
> +    datasetRevId!: string;
`datasetRevId!: Nullable<string>;`?

2024-12-27 11:19 UTC, sjorobekov commented on src/db/models/new/data-export/index.ts
> +    datasetRevId!: string;
Oops, added

2025-01-18 17:14 UTC, imsitnikov requested changes

2025-01-18 17:14 UTC, imsitnikov commented on src/db/migrations/20241219092946_data_export.ts
> +            chart_id BIGINT REFERENCES entries (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
`chart_id` and `chart_rev_id` should be ` NOT NULL`.

2025-01-20 16:04 UTC, sjorobekov commented on src/db/migrations/20241219092946_data_export.ts
> +            chart_id BIGINT REFERENCES entries (entry_id) ON UPDATE CASCADE ON DELETE SET NULL,
Discussed. Removed NOT NULL from `connection_id` and `connection_rev_id`

2025-01-21 13:16 UTC, imsitnikov commented on src/db/models/new/data-export/index.ts
> +    datasetId!: Optional<string>;
Would be better to use actual db types in the model. Each entry and revision ids are `Nullable<string>`.

2025-01-21 13:53 UTC, sjorobekov commented on src/db/models/new/data-export/index.ts
> +    datasetId!: Optional<string>;
updated

2025-01-21 14:25 UTC, imsitnikov submitted a review, later dismissed

2025-01-21 14:41 UTC, imsitnikov approved these changes

2025-01-21 14:55 UTC, merged