Add getEntriesData endpoint
datalens-tech/datalens-us pull request #227
Opened 2024-12-27 12:11 UTC by stepanenkoxx

2024-12-28 12:53 UTC, stepanenkoxx commented on src/controllers/entries/getEntriesData/types.ts
> +    scope: Nullable<EntryScope>;
У нас почему-то в модельке такой тип для scope
Он действительно может быть null?

2024-12-28 13:17 UTC, stepanenkoxx commented on src/registry/common/components/dls/types.ts
> +    checkBulkPermission<E extends object>(
There should probably be {entryId: string} not object
But we have some usages where entity type is {entryId?: string}

2024-12-28 14:03 UTC, stepanenkoxx commented on src/services/new/entry/get-joined-entries-revisions-by-ids.ts
> +                permission: WorkbookPermission.View,
Or it must be like this?

```
       permission: isEnabledFeature(ctx, Feature.UseLimitedView)
                ? WorkbookPermission.LimitedView
                : WorkbookPermission.View,
```

2025-01-13 11:58 UTC, stepanenkoxx commented on src/controllers/entries/getEntriesData/index.ts
> +        fields: z.string().array().min(1),
maybe it's worth limiting the maximum value too, but I don't know how much to set

2025-01-13 16:48 UTC, imsitnikov requested changes

2025-01-13 16:48 UTC, imsitnikov commented on src/controllers/entries/getEntriesData/response-model.ts
> +    notFoundEntryIds.forEach((entryId) => {
Can we keep the order of entries as in the  argument (`body.entryIds`)?

2025-01-16 08:21 UTC, stepanenkoxx commented on src/components/response-presenter.ts
> +export async function prepareResponseAsync<T extends any = any>({
discussed, decided to leave it for now

2025-01-16 08:22 UTC, stepanenkoxx commented on src/controllers/entries/getEntriesData/index.ts
> +    res: Response<GetEntriesDataResponseBody>,
discussed

2025-01-16 08:22 UTC, stepanenkoxx commented on src/services/new/entry/get-joined-entries-revisions-by-ids.ts
> +        if (workbookId && permittedWorkbookIds.includes(workbookId)) {
change array to map here

2025-01-17 16:44 UTC, imsitnikov requested changes

2025-01-17 16:44 UTC, imsitnikov commented on src/tests/int/env/platform/helpers.ts
> +export const createMockEntry = async (args: CreateMockEntryArgs = {}, options?: OptionsArgs) => {
Is it used?

2025-01-17 16:44 UTC, imsitnikov commented on src/services/new/entry/get-joined-entries-revisions-by-ids.ts
> +    const notFoundEntryIdsMap = entryIds.reduce<Record<string, string>>((acc, id) => {
looks like `notFoundEntryIdsMap` is not being used

2025-01-17 16:44 UTC, imsitnikov commented on src/services/new/entry/get-joined-entries-revisions-by-ids.ts
> +    const accessDeniedEntryIdsMap = _.keyBy<string>([
Can we use array here? `{ entry1Id: entry1Id, entry2Id: entry2Id }` looks excessive

2025-01-17 16:44 UTC, imsitnikov commented on src/services/new/entry/get-joined-entries-revisions-by-ids.ts
> +    entries: Record<string, JoinedEntryRevisionColumns | undefined>;
Can we return `{ entryId: undefined }`?

Considering the other comments it might look like this:
```ts
export type GetJoinedEntriesRevisionsByIdsResult = {
    entries: Record<string, JoinedEntryRevisionColumns>;
    accessDeniedEntryIds: string[];
};
```

2025-01-17 16:44 UTC, imsitnikov commented on src/controllers/entries/get-entries-data/index.ts
> +    req.ctx.log('GET_ENTRIES_DATA_REQUEST', {
Let's call it after `getJoinedEntriesRevisionsByIds(...)` and change message to `FILTERED_FIELDS`.

2025-01-17 17:50 UTC, stepanenkoxx commented on src/tests/int/env/platform/helpers.ts
> +export const createMockEntry = async (args: CreateMockEntryArgs = {}, options?: OptionsArgs) => {
forgot to delete when I moved folder tests

2025-01-17 17:53 UTC, imsitnikov approved these changes

2025-01-17 17:54 UTC, stepanenkoxx commented on src/services/new/entry/get-joined-entries-revisions-by-ids.ts
> +    entries: Record<string, JoinedEntryRevisionColumns | undefined>;
> Can we return { entryId: undefined }?

actually no)
but I just don't like that `entries['any_key']` always returns `JoinedEntryRevisionColumns` type

so here TS doesn't help us to see that entry could be `undefined`
https://github.com/datalens-tech/datalens-us/blob/ef5f4ca3a6e5e5daf70a67d55839899a96530b7a/src/controllers/entries/get-entries-data/response-model.ts#L50

but yeah, making `JoinedEntryRevisionColumns | undefined` is not good practice either )
removed `undefined`

2025-01-17 18:07 UTC, merged