Charts 8598 change workbook permission mapping
datalens-tech/datalens-us pull request #29
Opened 2023-11-16 18:13 UTC by Sergey-weber

Change behavior for method getEntryPermissionsByWorkbook
Change to syns 
added logic set permissions depends on entry scope

2023-11-17 09:52 UTC, imsitnikov requested changes

2023-11-17 09:52 UTC, imsitnikov commented on src/db/models/favorite/index.ts
> +                        includePermissionsInfo
If we don't have `includePermissionsInfo: true` we will not return any workbook entries, isn't it?

2023-11-17 09:52 UTC, imsitnikov commented on src/db/models/favorite/index.ts
> +                        workbooksMap.has(entry.workbookId) &&
Why are we doing this check? Here are only workbook entries.

2023-11-17 09:52 UTC, imsitnikov commented on src/db/models/favorite/index.ts
> +                            workbookPermissionsMap.set(workbook.model.workbookId, permissions);
We rewrite permissions for workbook for every entry, looks strange.

Can we replace `workbookPermissionsMap` with `entryPermissionsMap` and store there `entryId` -> `entryPermissions`?

2023-11-17 09:52 UTC, imsitnikov commented on src/db/models/navigation/index.ts
> +                        workbooksMap.has(entry.workbookId) &&
Same comments as for favorites

2023-11-17 09:52 UTC, imsitnikov commented on src/services/entry/actions/create-in-workbook.ts
> +    if (includePermissionsInfo) {
Can we combine two identical `if (includePermissionsInfo)`?

2023-11-17 09:52 UTC, imsitnikov commented on src/services/entry/actions/get-entry-relations.ts
> +            iamPermissions = getEntryPermissionsByWorkbook({
These are the permissions for the target entry and below they are used for all relative entries. It is not right.

2023-11-17 09:52 UTC, imsitnikov commented on src/services/new/entry/get-entry.ts
>                      iamPermissions = await getEntryPermissionsByWorkbook({
`await`?

2023-11-17 09:52 UTC, imsitnikov commented on src/services/new/workbook/get-workbook-content.ts
> +                    trx: targetTrx,
`trx`?

2023-11-17 14:34 UTC, Sergey-weber commented on src/services/entry/actions/get-entry-relations.ts
> +            iamPermissions = getEntryPermissionsByWorkbook({
added setting permissions for relations

2023-11-17 14:35 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +                        workbooksMap.has(entry.workbookId) &&
we discussed it and decided to leave it as it is

2023-11-20 09:43 UTC, imsitnikov commented on src/services/entry/actions/get-entry-relations.ts
> +                    const workbook = await getWorkbook(
No need to get a workbook for every entry. In most cases it will be the same workbook. Would be better to filter `relations` by workbookId from the target entry:
```typescript
let relations = await getRelatedEntries(ctx, {
    entryIds: [entryId],
    direction: validatedDirection,
});

if (entry.workbookId) {
    relations = relations.filter((relationEntry) => {
        return relationEntry.workbookId === entry.workbookId;
    });

    ...
} else {
```

2023-11-20 09:46 UTC, imsitnikov commented on src/services/entry/actions/get-entry-relations.ts
>      let iamPermissions: Optional<EntryPermissions>;
Let's put this variable in the loop where it's used.

2023-11-20 17:53 UTC, imsitnikov requested changes

2023-11-20 17:53 UTC, imsitnikov commented on src/services/entry/actions/get-entry-relations.ts
> +        relations = (await Promise.all(
Unnecessary `Promise.all` and `async` in `map` below.

2023-11-20 18:03 UTC, Sergey-weber commented on src/services/entry/actions/get-entry-relations.ts
> +        relations = (await Promise.all(
removed

2023-11-20 18:06 UTC, imsitnikov approved these changes

2023-11-21 06:59 UTC, merged