Add private route for restore workbook
datalens-tech/datalens-us pull request #31
Opened 2023-11-29 13:40 UTC by Sergey-weber

2023-12-02 15:25 UTC, imsitnikov requested changes

2023-12-02 15:25 UTC, imsitnikov commented on src/services/new/workbook/restore-workbook.ts
> +        .skipUndefined()
Is it needed here and below?

2023-12-02 15:25 UTC, imsitnikov commented on src/services/new/workbook/restore-workbook.ts
> +        .andWhereNot(WorkbookModelColumn.DeletedAt, null)
Let's check this after the query, like:

```typescript
if (!model) {
    throw new AppError(US_ERRORS.WORKBOOK_NOT_EXISTS, {
        code: US_ERRORS.WORKBOOK_NOT_EXISTS,
    });
}

if (model.deletedAt !== null) {
    throw new AppError(US_ERRORS.WORKBOOK_IS_ALREADY_RESTORED, { // new error with 400 status
        code: US_ERRORS.WORKBOOK_IS_ALREADY_RESTORED,
    });
}
```

2023-12-02 15:25 UTC, imsitnikov commented on src/services/new/workbook/restore-workbook.ts
> +        await Promise.all(
We can restore all  the entries by one patch query:

```sql
UPDATE entries SET
	key = regexp_replace(key, '__trash/', ''),
	display_key = regexp_replace(display_key, '__trash/', ''),
	inner_meta = inner_meta - 'oldKey' - 'oldDisplayKey',
	is_deleted = FALSE,
	deleted_at = NULL,
	updated_at = NOW()
WHERE
	tenant_id = '{TENANT_ID}' AND workbook_id = {WORKBOOK_ID} AND deleted_at > '{WORKBOOK_DELETED_AT}';
```

And getting all the entries above will be unnecessary.

2023-12-06 14:16 UTC, Sergey-weber commented on src/services/new/workbook/restore-workbook.ts
> +        .skipUndefined()
unnessesary, fixed it, was error when don't have undefined

2023-12-06 20:48 UTC, imsitnikov approved these changes

2023-12-07 06:26 UTC, merged