Add join favorites for getting workbook entries
datalens-tech/datalens-us pull request #47
Opened 2023-12-20 15:35 UTC by Sergey-weber

Add select field - isFavorite for getting workbook entries,
Add join favorites table for getting workbook entries

2023-12-23 14:48 UTC, imsitnikov requested changes

2023-12-23 14:48 UTC, imsitnikov commented on src/services/new/workbook/get-workbook-content.ts
> +        .select(selectColumnNames)
Can we use `JoinedEntryRevisionFavorite` here for type safety?

2023-12-23 14:48 UTC, imsitnikov commented on src/services/new/workbook/get-workbook-content.ts
> +            Favorite.query(targetTrx).select('favorites.entryId').as('sub'),
It isn't correct subquery because for getting `isFavorite` we have to check `login` and `tenantId` too.
This query checks that someone added this entry to favorites, not current user.

2023-12-25 12:39 UTC, Sergey-weber commented on src/services/new/workbook/get-workbook-content.ts
> +            Favorite.query(targetTrx).select('favorites.entryId').as('sub'),
added login and tenant for query

2023-12-25 12:40 UTC, Sergey-weber commented on src/services/new/workbook/get-workbook-content.ts
> +        .select(selectColumnNames)
could you explain more please, where you wanna use JoinedEntryRevisionFavorite?  for select fields like entry_id in favorite table?

2023-12-28 13:17 UTC, Sergey-weber commented on src/services/new/workbook/get-workbook-content.ts
> +        .select(selectColumnNames)
added new method for getting list with pagination - findWithPagination, because if we try to extends class with same same static method types stop converging

2024-01-03 16:42 UTC, imsitnikov requested changes

2024-01-03 16:42 UTC, imsitnikov commented on src/services/new/workbook/get-workbook-content.ts
> +    const entriesPage = await JoinedEntryRevisionFavorite.findWithPagination({
As we discussed, `JoinedEntryRevisionFavorite` doesn't suitable here. Would be better to add a new presentation without joined revision info – `JoinedEntryFavorite`. And remove unnecessary params `revId` and `branch` in the `getWorkbookContent` service.

2024-01-22 20:13 UTC, imsitnikov commented on src/services/new/workbook/get-workbook-content.ts
> +    branch?: 'saved' | 'published';
Need to delete these params. In `JoinedEntryRevisionFavorite` below we should use the default join strategy for entries.

2024-01-22 20:33 UTC, imsitnikov commented on src/db/presentations/joined-entry-favorite/index.ts
> +    static findPage({
Let's add `find` and `findOne` methods too.
Just like in `JoinedEntryRevisionFavorite`.

2024-01-22 20:43 UTC, imsitnikov commented on src/services/new/workbook/formatters/format-get-workbook-content.ts
> +    ctx: CTX,
`ctx` isn't used

2024-01-22 20:51 UTC, imsitnikov commented on src/services/new/workbook/get-workbook-content.ts
> +            builder.where({
Let's add `tenantId` and `projectId` checks:

```ts
 builder.where({
    tenantId,
    projectId,
    workbookId: workbookId,
    isDeleted: false,
});
```

2024-01-22 21:00 UTC, imsitnikov commented on src/services/new/workbook/get-workbook-content.ts
> +        joinRevisionArgs: {
Need to remove this arg and correct types in methods:

<img width="526" alt="image" src="https://github.com/datalens-tech/datalens-us/assets/29424746/508aa38b-1078-4107-899d-b7a59188933f">

2024-01-23 12:16 UTC, imsitnikov approved these changes

2024-01-23 12:46 UTC, merged