Charts 8294 entry list add checking permissions for workbooks entry
datalens-tech/datalens-us pull request #5
Opened 2023-09-26 07:47 UTC by Sergey-weber

2023-09-29 11:06 UTC, imsitnikov requested changes

2023-10-03 09:23 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    logInfo(ctx, 'GET WORKBOOKS LIST BY IDS FINISHED', {
fixed

2023-10-03 09:23 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    logInfo(ctx, 'GET WORKBOOKS LIST BY IDS STARTED', {
fixed

2023-10-03 09:23 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +        const workbookEntries: Favorite[] = [];
yes, i implemented the map for getting entities with the right order

2023-10-03 09:24 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +        if (workbookEntries.length && checkWorkbookEnabled) {
fixed

2023-10-03 09:24 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +        if (!ctx.config.dlsEnabled && result.length > 0) {
fixed

2023-10-03 09:24 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +    workbookId!: string | null;
moved prop workbookId to FavoriteColumns

2023-10-03 09:27 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    for await (const pair of workbooksMap) {
actually now solution better than Promise.all(workbooksMap.map(...)), because we have to check throw in try/catch, it can help us getting entries with right permission, without frontend can get permission denied, let's leave it as it is

2023-10-03 09:28 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +        parents.forEach((parent: CollectionModel) => {
unnecessary, moved outside loop

2023-10-03 09:28 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +        const collectionId =
yes, used model.collectionId

2023-10-03 09:28 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    workbookList.forEach(async (model) => {
fixed

2023-10-03 09:28 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    const collectionIds: Nullable<string>[] | [] = workbookList
fixed

2023-10-03 09:28 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    if ((!accessServiceEnabled && skipCheckPermissions) || isPrivateRoute) {
fixed

2023-10-03 09:28 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +            [WorkbookModelColumn.TenantId]: tenantId,
added [WorkbookModelColumn.ProjectId]: projectId

2023-10-03 09:29 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +): Promise<WorkbookModel[]> => {
removed Promise<WorkbookModel[]>

2023-10-03 09:31 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +export const getParentsByIds = async ({ctx, trx, collectionIds}: GetParentsArgs) => {
yes, looks good, added getCollectionsParentIds, and modified get-parents.ts, but i guess we can leave  name - getParentIds, cause a lot of method use these name, we can do that in another pr

2023-10-03 09:31 UTC, Sergey-weber commented on src/db/models/navigation/index.ts
> +            if (ctx.config.dlsEnabled && entryWithoutWorkbook.length) {
fixed

2023-10-03 14:01 UTC, imsitnikov requested changes

2023-10-03 14:01 UTC, imsitnikov commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    for await (const pair of workbooksMap) {
Definitely the current solution is not better because all `checkPermission` will be executed one after another. These requests must be parallel.

We can replace `try {} catch(err) {}` with `then` / `catch` and use `Promise.all`:

```typescript
const checkPermissionPromises: Promise<WorkbookModel | void>[] = [];

workbooksMap.forEach((parentIds, workbookModel) => {
    const workbook = new Workbook({
        ctx,
        model: workbookModel,
    });

    const promise = workbook
        .checkPermission({
            parentIds,
            permission: isEnabledFeature(ctx, Feature.UseLimitedView)
                ? WorkbookPermission.LimitedView
                : WorkbookPermission.View,
        })
        .then(() => {
            return workbookModel;
        })
        .catch(() => {});

    checkPermissionPromises.push(promise);
});

const responses = await Promise.all(checkPermissionPromises);
const result = responses.filter((item) => Boolean(item)) as WorkbookModel[];
```

2023-10-04 07:05 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    const map: {[key: string]: string | null} = {};
yew sure, changed on new Map()

2023-10-04 07:05 UTC, Sergey-weber commented on src/db/models/navigation/index.ts
> +        const checkWorkbookEnabled = !onlyPublic && !isEmbedding;
removed

2023-10-04 07:05 UTC, Sergey-weber commented on src/db/models/navigation/index.ts
> +            if (ctx.config.accessServiceEnabled && checkWorkbookEnabled) {
fixed

2023-10-04 07:05 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +                        result.push(entry);
added isLocked: false

2023-10-04 07:05 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    for await (const pair of workbooksMap) {
ok, fixed it on Promise.all

2023-10-04 08:51 UTC, imsitnikov approved these changes

2023-10-04 09:13 UTC, merged