Add new migration for billing
datalens-tech/datalens-us pull request #66
Opened 2024-01-25 20:11 UTC by Sergey-weber

2024-01-30 09:29 UTC, imsitnikov requested changes

2024-01-30 09:29 UTC, imsitnikov commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        ALTER TABLE tenants ADD COLUMN account_billing_id BIGINT DEFAULT NULL;
1) `account_billing_id` -> `billing_account_id`
2) `BIGINT` -> `TEXT` (the same type as `tenant_id`)

2024-01-30 09:29 UTC, imsitnikov commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        ALTER TABLE tenants ADD COLUMN instance_service_billing_id BIGINT DEFAULT NULL;
1) `instance_service_billing_id ` -> `billing_instance_service_id`
2) `BIGINT` -> `TEXT` (the same type as `tenant_id`)
3) Need to research about auto filling this column with cloud id.

2024-01-30 09:29 UTC, imsitnikov commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        ALTER TABLE tenants DROP COLUMN billing_rate;
Good practice is to use the reverse order of the delete commands: `billing_started_at`, `instance_service_billing_id`, `account_billing_id`, `billing_rate`, `BILLING_RATE_TYPE `.

2024-01-30 10:41 UTC, jhoncool commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        DROP TYPE IF EXISTS BILLING_RATE_TYPE;
No need `IF EXISTS`

2024-01-30 13:09 UTC, stankis requested changes

2024-01-30 13:09 UTC, stankis commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        ALTER TABLE tenants ADD COLUMN billing_rate BILLING_RATE_TYPE not null default('community');
I'm just interested: have you considered the idea to have billing table instead of adding several billing-related columns to tenants table?

2024-01-30 18:15 UTC, Sergey-weber commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        DROP TYPE IF EXISTS BILLING_RATE_TYPE;
ok, fixed it

2024-01-30 18:15 UTC, Sergey-weber commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        ALTER TABLE tenants ADD COLUMN billing_rate BILLING_RATE_TYPE not null default('community');
yup, fix it, thanks

2024-01-30 18:54 UTC, stankis approved these changes

2024-01-31 17:43 UTC, imsitnikov requested changes

2024-01-31 17:43 UTC, imsitnikov commented on src/db/migrations/20240124144536_add_billing_columns_to_tenants.ts
> +        DROP INDEX tenants_billing_instance_service_id_idx;
Should be on the first row, reverse order in `down` method

2024-01-31 18:47 UTC, imsitnikov approved these changes

2024-02-01 09:42 UTC, merged