Charts 8474 route copy workbook optimize performance requests to postgresql
datalens-tech/datalens-us pull request #7
Opened 2023-10-04 14:42 UTC by Sergey-weber

2023-10-08 15:10 UTC, imsitnikov requested changes

2023-10-09 08:39 UTC, Sergey-weber commented on src/services/new/workbook/copy-workbook.ts
> +    const originWorkbookModel: Optional<WorkbookModel> = await WorkbookModel.query(targetTrx)
the target trx uses getReplace internally by default, I think it's a good practice if we will want to use this method in a transaction

2023-10-09 10:20 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> +        entryIds: result.map(({newJoinedEntryRevision}) =>
changed on forEach

2023-10-09 10:20 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> -            await Link.sync({entryId: newEntryId, links, ctx, trxOverride: transactionTrx});
added skipLinkSync

2023-10-09 10:20 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> -    if (!skipWorkbookPermissionsCheck) {
fixed

2023-10-09 10:21 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> +    const mapEntryIdsWithOldIds: {[key: string]: string} = {};
fixed

2023-10-09 10:21 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> +            type: 'array',
fixed

2023-10-09 10:22 UTC, Sergey-weber commented on src/services/new/workbook/copy-workbook.ts
>          .findById(workbookId)
added

2023-10-09 10:23 UTC, Sergey-weber commented on src/services/new/workbook/copy-workbook.ts
>          if (accessServiceEnabled && accessBindingsServiceEnabled) {
fixed

2023-10-09 11:25 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> +    const originJoinedEntryRevisions = await (JoinedEntryRevision.query(Entry.replica)
we don't have method whereIn in Joined Entry Revision.find, can we provide these in another ticket, we have to understand how we want to realise this method and typings?

2023-10-09 11:39 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> +    const originJoinedEntryRevisions = await (JoinedEntryRevision.query(Entry.replica)
added new method whereIn in JoinedEntryRevision

2023-10-09 11:39 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> +    const copiedJoinedEntryRevisions = await (JoinedEntryRevision.query(transactionTrx)
fixed

2023-10-11 16:23 UTC, imsitnikov requested changes

2023-10-12 14:47 UTC, Sergey-weber commented on src/services/new/workbook/copy-workbook.ts
> +        const workbook = new Workbook({
fixed

2023-10-12 14:47 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> -    if (!skipWorkbookPermissionsCheck) {
added checking permissions and same workbook id for entries

2023-10-12 14:47 UTC, Sergey-weber commented on src/services/new/workbook/copy-workbook.ts
> +    const originWorkbookModel: Optional<WorkbookModel> = await WorkbookModel.query(targetTrx)
fixed

2023-10-12 17:27 UTC, imsitnikov requested changes

2023-10-12 17:27 UTC, imsitnikov commented on src/services/entry/actions/copy-to-workbook.ts
> +    const workbookId = originJoinedEntryRevisions[0].workbookId;
Some checks aren't needed when using an array of records, and some checks can be moved from an asynchronous loop to a synchronous one. I suggest this:

```ts
if (originJoinedEntryRevisions.length === 0) {
    throw new AppError("Entries don't exist", {
        code: US_ERRORS.NOT_EXIST_ENTRY,
    });
}

let workbookId: Optional<string>;
originJoinedEntryRevisions.forEach((joinedEntryRevision) => {
    if (tenantIdOverride === undefined && joinedEntryRevision.tenantId !== tenantId) {
        throw new AppError(
            `Entry ${Utils.encodeId(joinedEntryRevision.entryId)} doesn't exist`,
            {
                code: US_ERRORS.NOT_EXIST_ENTRY,
            },
        );
    }

    if (joinedEntryRevision.scope === 'folder') {
        throw new AppError('Folders cannot be copied', {
            code: US_ERRORS.FOLDER_COPY_DENIED,
        });
    }

    if (joinedEntryRevision.workbookId === null) {
        throw new AppError(
            `Entry ${Utils.encodeId(
                joinedEntryRevision.entryId,
            )} doesn't have a workbookId and cannot be copied to a workbook.`,
            {
                code: US_ERRORS.ENTRY_WITHOUT_WORKBOOK_ID_COPY_DENIED,
            },
        );
    }

    if (workbookId === undefined) {
        workbookId = joinedEntryRevision.workbookId;
    } else if (joinedEntryRevision.workbookId !== workbookId) {
        throw new AppError(
            `Copying entries from different workbooks is denied – ${Utils.encodeId(
                workbookId,
            )} and ${Utils.encodeId(joinedEntryRevision.workbookId)}`,
            {
                code: US_ERRORS.ENTRIES_WITH_DIFFERENT_WORKBOOK_IDS_COPY_DENIED, // <-- new error code
            },
        );
    }
});

if (workbookId === undefined) {
    throw new AppError(`Entries don't have a workbookId and cannot be copied to a workbook.`, {
        code: US_ERRORS.ENTRY_WITHOUT_WORKBOOK_ID_COPY_DENIED,
    });
}

const mapEntryIdsWithOldIds = new Map<string, string>();

const newEntries = await Promise.all(
    originJoinedEntryRevisions.map(async (originJoinedEntryRevision) => {
        const [newEntryId, newRevId] = await Promise.all([getId(), getId()]);

        ...
    }),
);

if (!skipWorkbookPermissionsCheck) { // <-- no need to check workbookId
	...
}
```

2023-10-13 07:58 UTC, Sergey-weber commented on src/services/entry/actions/copy-to-workbook.ts
> +    const workbookId = originJoinedEntryRevisions[0].workbookId;
yea, fixed it

2023-10-13 09:51 UTC, imsitnikov approved these changes

2023-10-13 09:54 UTC, merged