Add migration for change index tenants_billing_instance_service_id_id on UNIQUE
datalens-tech/datalens-us pull request #76
Opened 2024-02-16 10:49 UTC by Sergey-weber

2024-02-16 17:50 UTC, imsitnikov requested changes

2024-02-16 17:50 UTC, imsitnikov commented on src/db/migrations/20240216103536_change_index_on_unique_for_billing_instance_service_id.ts
> +        ON tenants USING
```
ON tenants (billing_instance_service_id); 
```
We are not going to sort by this field, BTREE is not needed, and all previous unique indexes were without BTREE.

2024-02-16 19:10 UTC, Sergey-weber commented on src/db/migrations/20240216103536_change_index_on_unique_for_billing_instance_service_id.ts
> +        ON tenants USING
if we use a command like CREATE INDEX, it will use the BTREE index by default, it is good practice to explicitly specify which index.  BTREE is the most common index, it is used everywhere in our project, it is just not explicitly specified, a hash index may be suitable for our case, it only has the = operator, we just need to compare, but in practice it does not benefit much from the speed of BTREE

2024-02-19 09:28 UTC, jhoncool approved these changes

2024-02-19 09:29 UTC, imsitnikov approved these changes

2024-02-19 10:27 UTC, merged