feat: add bulkFetchWorkbooksAllPermissions for getWorkbooksListByIds,…
datalens-tech/datalens-us pull request #8
Opened 2023-10-06 15:32 UTC by Sergey-weber

Added bulkFetchWorkbooksAllPermissions in getWorkbooksListByIds
Added mapping permissions for entries with workbooks

2023-10-11 17:08 UTC, imsitnikov requested changes

2023-10-11 17:08 UTC, imsitnikov commented on src/db/models/favorite/index.ts
> +                    if (entry?.workbookId && workbookPermissionsMap.has(entry.workbookId)) {
Would be better to check `if (entry?.workbookId && workbookIds.includes(entry.workbookId)) {` because `workbookPermissionsMap` might be empty if  `includePermissionsInfo  === false`.

2023-10-11 17:08 UTC, imsitnikov commented on src/db/models/favorite/index.ts
> +                            permissions: workbookPermissionsMap.get(entry.workbookId),
`permissions: includePermissionsInfo ? workbookPermissionsMap.get(entry.workbookId) : undefined`

2023-10-11 17:08 UTC, imsitnikov commented on src/db/models/navigation/index.ts
> -            if (!isPrivateRoute && ctx.config.accessServiceEnabled) {
Why did you delete `!isPrivateRoute` check?

2023-10-13 09:19 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +        trx,
fixed

2023-10-13 09:19 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +                        includePermissionsInfo: true,
fixed

2023-10-13 09:19 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +                await Promise.all(
fixed

2023-10-13 09:19 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +                    if (entry?.workbookId && workbookPermissionsMap.has(entry.workbookId)) {
fixed

2023-10-13 09:19 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +                            permissions: workbookPermissionsMap.get(entry.workbookId),
fixed

2023-10-13 09:19 UTC, Sergey-weber commented on src/db/models/navigation/index.ts
> -            if (!isPrivateRoute && ctx.config.accessServiceEnabled) {
fixed

2023-10-13 09:19 UTC, Sergey-weber commented on src/entities/workbook/types.ts
> +export type WorkbookPermissions = {
fixed

2023-10-13 09:19 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
>          workbookIds: workbookIds.map((id) => Utils.encodeId(id)),
fixed

2023-10-13 09:20 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +                    const res: WorkbookInstance[] = await bulkFetchWorkbooksAllPermissions(ctx, [
added call bulkFetchWorkbooksAllPermissions outside loop

2023-10-13 14:39 UTC, imsitnikov requested changes

2023-10-13 14:39 UTC, imsitnikov commented on src/db/models/favorite/index.ts
> +                        includePermissionsInfo,
`getWorkbooksListByIds(...)` should return `WorkbookInstance[]`. Because there is no `permissions` field in `WorkbookModel`.

2023-10-13 14:39 UTC, imsitnikov commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +                workbooksMap.delete(workbookModel);
Deleting from an array while iterating that array looks bad...

2023-10-13 14:39 UTC, imsitnikov commented on src/db/models/navigation/index.ts
>                              isLocked: false,
I think `isLocked` should be `true` if we don't have `read` permission.

2023-10-16 12:21 UTC, Sergey-weber commented on src/db/models/navigation/index.ts
>                              isLocked: false,
added conditions for isLocked

2023-10-16 12:22 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
> +                        includePermissionsInfo,
yea, fixed on returning WorkbookInstance[]

2023-10-16 13:00 UTC, imsitnikov commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +        acceptedWorkbooksMap.forEach((parentIds, workbookModel) => {
```ts
acceptedWorkbooksMap.forEach((parentIds, workbookModel) => {
    mappedWorkbooks.push({
        model: workbookModel,
        parentIds,
    });
});
```

2023-10-16 13:00 UTC, imsitnikov commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    const result: WorkbookInstance[] = workbooks.filter((item) =>
`const result = workbooks.filter((item) => Boolean(item)) as WorkbookInstance[];`

2023-10-16 13:01 UTC, imsitnikov commented on src/db/models/favorite/index.ts
>                          workbookIds: workbookEntries.map((entry) => entry.workbookId),
`workbookIds: workbookEntries.map((entry) => entry.workbookId) as string[],`

2023-10-16 13:32 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
>      workbookIds: Nullable<string>[];
fixed

2023-10-16 13:32 UTC, Sergey-weber commented on src/db/models/favorite/index.ts
>                          workbookIds: workbookEntries.map((entry) => entry.workbookId),
fixed

2023-10-16 13:32 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +    const result: WorkbookInstance[] = workbooks.filter((item) =>
fixed

2023-10-16 13:32 UTC, Sergey-weber commented on src/services/new/workbook/get-workbooks-list-by-ids.ts
> +        acceptedWorkbooksMap.forEach((parentIds, workbookModel) => {
fixed

2023-10-16 13:35 UTC, imsitnikov approved these changes

2023-10-16 13:43 UTC, merged