Add a feature to copy entries to workbooks
datalens-tech/datalens-us pull request #9
Opened 2023-10-09 14:18 UTC by bt4R9

I've added a new feature that allows to copy entries to workbooks.
Tests will be added later to this PR.

2023-10-09 14:21 UTC, bt4R9 commented on src/services/new/entry/copy-entries-to-workbook.ts
> +            code: US_ERRORS.ACCESS_SERVICE_PERMISSION_DENIED,
What will be the correct error code in this case?

2023-10-09 14:26 UTC, bt4R9 commented on src/services/new/workbook/copy-workbook.ts
> +    const copiedJoinedEntryRevisions = await Promise.all(
Do we have any limitations here? It seems like running multiple inserts in parallel is not the best idea, however have we ever encountered any related issues?

2023-10-11 17:36 UTC, imsitnikov requested changes

2023-10-11 17:36 UTC, imsitnikov commented on src/components/middlewares/decode-id.ts
> +                if (Array.isArray(entity)) {
Is this for cases when in fields like `entryId` or `workbookId` will be an array? Looks strange.

2023-10-11 17:36 UTC, imsitnikov commented on src/const/common.ts
> +    'key as displayKey',
Why did you add `key as displayKey`?

2023-10-11 17:36 UTC, imsitnikov commented on src/services/new/entry/utils/resolveNameCollisions.ts
> +export const reolveEntriesNameCollisions = ({
Let's use this method in `migrateEntriesToWorkbook`

2023-10-11 17:36 UTC, imsitnikov commented on src/services/new/entry/copy-entries-to-workbook.ts
> +export const copyEntriesToWorkbook = async (
This method has already been implemented in – https://github.com/datalens-tech/datalens-us/pull/7
Let's wait for it to be merged and reuse it.

2023-10-18 13:32 UTC, bt4R9 commented on src/services/new/entry/utils/resolveNameCollisions.ts
> +export const reolveEntriesNameCollisions = ({
It's in the closed source, maybe in the different pr?

2023-10-18 15:58 UTC, imsitnikov requested changes

2023-10-18 15:58 UTC, imsitnikov commented on src/const/common.ts
> +    'publishedId',
Are `publishedId` and `saveId` still needed here?

2023-10-18 15:58 UTC, imsitnikov commented on src/routes.ts
> +                route: 'POST /v2/entries/copy',
`POST /v2/entries/copy` is not a good name because it will conflict with `POST /v2/entries/:entryId` in the future. I would suggest – `POST /v2/copy-entries`.

2023-10-18 18:11 UTC, imsitnikov requested changes

2023-10-18 18:11 UTC, imsitnikov commented on src/services/new/entry/copy-entries-to-workbook.ts
> +        const isFile = entry.type === EntryType.File || entry.type === EntryType.GsheetsV2;
file connectors here should throw the error `US_ERRORS.WORKBOOK_COPY_FILE_CONNECTION_ERROR` here

2023-10-18 18:11 UTC, imsitnikov commented on src/services/new/entry/copy-entries-to-workbook.ts
> +    if (!sourceEntry.workbookId) {
Here we need to check all entries, not just the first one

2023-10-31 13:55 UTC, imsitnikov requested changes

2023-10-31 13:55 UTC, imsitnikov commented on src/services/entry/actions/copy-to-workbook.ts
> +                [EntryColumn.TenantId]: tenantId,
Add `[EntryColumn.ProjectId]: projectId,` plz

2023-11-01 10:25 UTC, imsitnikov approved these changes

2023-11-01 10:43 UTC, Sergey-weber approved these changes

2023-11-01 11:15 UTC, merged